# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_pill_link_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeateveryday',
            name='pill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='everyday', to='data.Pill'),
        ),
        migrations.AlterField(
            model_name='repeateverynthday',
            name='pill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='everynday', to='data.Pill'),
        ),
        migrations.AlterField(
            model_name='time',
            name='pill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='data.Pill'),
        ),
        migrations.AlterField(
            model_name='weekdaysrepetion',
            name='pill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wdays', to='data.Pill'),
        ),
    ]
